[build]
  command = "pnpm run netlify:build"
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["build/server/**", ".env"]

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
