import type { Metadata } from 'next';
import '../styles/globals.scss';
import { UpProvider } from '../components/upProvider';

export const metadata: Metadata = {
  title: 'LUKSO MiniApp Nextjs Template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UpProvider>
          {children}
        </UpProvider>
      </body>
    </html>
  );
}
